version: "3.9"

services:
  custos1:
    build: ./docker
    container_name: custos1
    ports:
      - "8001:8000"
    environment:
      - NODE_ID=1

  custos2:
    build: ./docker
    container_name: custos2
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=2
